services:
  frontend:
    build: ./frontend
    env_file:
      - ./backend/.env.sample
    ports:
      - "5173:5173"  
    networks:
      - mern_network

  backend:
    build: ./backend
    env_file:
      - ./backend/.env.sample
    ports:
      - "5000:5000" 
    networks:
      - mern_network
    depends_on:
      - mongodb
    
  mongodb:
    image: mongo:latest  
    ports:
      - "27017:27017"  
    networks:
      - mern_network
    volumes:
      - ./backend/data:/data  

networks:
  mern_network:
    driver: bridge
